# Generated by Django 4.2.6 on 2023-12-08 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_asset_profile_portfolio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='risk_aversion',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
    ]
