# Generated by Django 4.2.6 on 2023-12-14 06:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_profile_risk_aversion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='portfolio',
            name='assets',
        ),
        migrations.AddField(
            model_name='asset',
            name='portfolio',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assets', to='app.portfolio'),
        ),
    ]
