# Generated by Django 4.2.6 on 2023-12-14 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_remove_portfolio_assets_asset_portfolio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='alpha',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='asset',
            name='beta',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='asset',
            name='ticker',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
