# Generated by Django 4.2.6 on 2023-12-19 07:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_asset_alpha_alter_asset_beta_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asset',
            name='allocation',
        ),
        migrations.RemoveField(
            model_name='asset',
            name='portfolio',
        ),
        migrations.CreateModel(
            name='PortfolioAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.asset')),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.portfolio')),
            ],
        ),
    ]
