# Generated by Django 4.2.6 on 2023-12-19 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_remove_asset_allocation_remove_asset_portfolio_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='portfolioasset',
            name='asset',
        ),
        migrations.AddField(
            model_name='portfolioasset',
            name='asset_ticker',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
