# Generated by Django 4.2.6 on 2023-12-19 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_remove_portfolioasset_asset_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolioasset',
            name='date_added',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
