# Generated by Django 4.2.6 on 2023-12-20 17:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_portfolioasset_date_added'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolioasset',
            name='portfolio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assets', to='app.portfolio'),
        ),
    ]
