# Generated by Django 4.2.6 on 2023-12-22 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_alter_portfolioasset_portfolio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asset',
            name='alpha',
        ),
        migrations.RemoveField(
            model_name='asset',
            name='beta',
        ),
        migrations.AddField(
            model_name='asset',
            name='country',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='asset',
            name='currency',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='asset',
            name='exchange',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='asset',
            name='isin',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='asset',
            name='type',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
