# Generated by Django 4.2.6 on 2023-12-23 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_remove_asset_alpha_remove_asset_beta_asset_country_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='expected_market_return',
            field=models.DecimalField(blank=True, decimal_places=5, help_text='Annual expected return of the market', max_digits=7, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='market_index',
            field=models.CharField(blank=True, help_text='Ticker symbol of the market index used for calculations', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='risk_free_rate',
            field=models.DecimalField(blank=True, decimal_places=5, help_text='Annual risk-free rate of return', max_digits=7, null=True),
        ),
    ]
