# Generated by Django 4.2.6 on 2023-12-23 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_profile_expected_market_return_profile_market_index_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='investment_time_period',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='market_index',
            field=models.CharField(help_text='Ticker symbol of the market index used for calculations', max_length=10, null=True),
        ),
    ]
