# Generated by Django 4.2.6 on 2023-12-28 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_profile_investment_time_period_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asset',
            name='currency',
        ),
        migrations.RemoveField(
            model_name='asset',
            name='isin',
        ),
        migrations.AddField(
            model_name='asset',
            name='delistingDate',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='asset',
            name='ipoDate',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='asset',
            name='status',
            field=models.CharField(choices=[('Active', 'Active'), ('Delisted', 'Delisted')], default='Active', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='asset',
            name='country',
            field=models.CharField(default='USA', max_length=100),
        ),
        migrations.AlterField(
            model_name='asset',
            name='ticker',
            field=models.CharField(max_length=10),
        ),
    ]
