# Generated by Django 4.2.6 on 2023-12-28 19:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_remove_asset_currency_remove_asset_isin_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Stock',
        ),
    ]
