# Generated by Django 4.2.6 on 2024-03-10 18:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_profile_profile_picture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asset',
            name='delistingDate',
        ),
        migrations.RemoveField(
            model_name='asset',
            name='ipoDate',
        ),
        migrations.RemoveField(
            model_name='asset',
            name='status',
        ),
        migrations.RemoveField(
            model_name='asset',
            name='type',
        ),
        migrations.RemoveField(
            model_name='portfolio',
            name='alpha',
        ),
        migrations.RemoveField(
            model_name='portfolio',
            name='beta',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='expected_market_return',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='investment_time_period',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='market_index',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='risk_aversion',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='risk_free_rate',
        ),
        migrations.AddField(
            model_name='asset',
            name='industry',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='asset',
            name='ipoYear',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='asset',
            name='sector',
            field=models.CharField(blank=True, choices=[('Finance', 'Finance'), ('Health Care', 'Health Care'), ('Telecommunications', 'Telecommunications'), ('Basic Materials', 'Basic Materials'), ('Industrials', 'Industrials'), ('Consumer Staples', 'Consumer Staples'), ('Utilities', 'Utilities'), ('Real Estate', 'Real Estate'), ('Energy', 'Energy'), ('Consumer Discretionary', 'Consumer Discretionary'), ('Technology', 'Technology'), ('Miscellaneous', 'Miscellaneous')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='investment_time_period',
            field=models.CharField(choices=[('1month', '1 Month'), ('3month', '3 Months'), ('6month', '6 Months'), ('1year', '1 Year'), ('3year', '3 Years'), ('5year', '5 Years'), ('10year', '10 Years'), ('30year', '30 Years')], max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='market_index',
            field=models.CharField(blank=True, help_text='Ticker symbol of the market index used for calculations', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='risk_aversion',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(4)]),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='sell_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='status',
            field=models.CharField(blank=True, choices=[('ACTIVE', 'Active'), ('SOLD', 'Sold')], max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='portfolioasset',
            name='asset_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='portfolioasset',
            name='date_sold',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='asset',
            name='country',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='asset',
            name='exchange',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='portfolioasset',
            name='asset_ticker',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
