# Generated by Django 4.2.6 on 2024-03-10 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_remove_asset_delistingdate_remove_asset_ipodate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='asset_type',
            field=models.CharField(blank=True, choices=[('ETF', 'ETF'), ('Stock', 'Stock')], max_length=10, null=True),
        ),
    ]
