# Generated by Django 4.2.6 on 2024-03-10 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_asset_asset_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='sector',
            field=models.CharField(blank=True, choices=[('Finance', 'Finance'), ('Healthcare', 'Healthcare'), ('Telecommunications', 'Telecommunications'), ('Basic Materials', 'Basic Materials'), ('Industrials', 'Industrials'), ('Consumer Staples', 'Consumer Staples'), ('Utilities', 'Utilities'), ('Real Estate', 'Real Estate'), ('Energy', 'Energy'), ('Consumer Discretionary', 'Consumer Discretionary'), ('Technology', 'Technology'), ('Miscellaneous', 'Miscellaneous')], max_length=50, null=True),
        ),
    ]
