# Generated by Django 4.2.6 on 2024-03-16 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_alter_asset_sector'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='sector',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
