# Generated by Django 4.2.6 on 2024-03-17 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_transaction_delete_portfolioasset'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='transaction_date',
            field=models.DateField(null=True),
        ),
    ]
